#!/usr/bin/env bash
#check

filepath="9-to_file_or_not_to_file"
if [ -e $filepath ]; then
	echo "school file exists"
	if [ -s $filepath ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $filepath ]; then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
