#!/usr/bin/env bash
sudo sed -i '/^127.0.0.1/s/$/ localhost.localdomain localhost2' /etc/hosts
sudo sed -i 's/^127.0.0.1\s*localhost$/127.0.0.1 localhost.localdomain/' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
sudo systemctl restart docker
